// Generated by https://quicktype.io

export interface Address {
  mapServletResponse: MapServletResponse;
  responseDTO:        ResponseDTO;
}

export interface MapServletResponse {
  data: { [key: string]: string };
}

export interface ResponseDTO {
  query:           string;
  code:            string;
  message:         string;
  tecnicalMessage: string;
  idTransaction:   string;
  status:          string;
  tenicalDetail:   any[];
}
